name: "Setup Node.js and install dependencies"
description: "Checks out code, sets up Node.js, and installs npm dependencies"
runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "npm"

    - name: Install dependencies 📦
      run: npm ci
