name: CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - id: publish
        name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false

      - name: Post-publish
        if: steps.publish.outputs.type
        run: |
          echo "Published ${{ steps.publish.outputs.type }} version: ${{ steps.publish.outputs.version }}"

      - name: Publish skipped
        if: steps.publish.outputs.type == ''
        run: |
          echo "Version in package.json has not changed. Skipping."
          exit 0

      - name: Create Github release
        if: steps.publish.outputs.type
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.publish.outputs.version }}
          name: v${{ steps.publish.outputs.version }}
          body: |
            New version: ${{ steps.publish.outputs.version }}
          draft: false
          prerelease: false
          token: ${{ secrets.PAT }}
